### PR TITLE
updated to work with Laravel 5.2 session component

### PR DESCRIPTION
**Pull request by nbsoftware**
Hello Andrew,
Here are a few modifications to make it work on Laravel 5.
Could/would you include those in your original repo?
Thanks
Fred

### CODE REVIEW

**Comment by silentworks** [comment]
Thanks for this @nbsoftware I will definitely merge this in.

**Comment by nbsoftware** [comment]
Thanks!
Do you plan to release the updated version on Packagist?
This would help referencing the package in the standard way rather than mentioning the dev-master branch.

**Comment by silentworks** [comment]
@nbsoftware yeah will try and do that between today and the weekend.

**Comment by nbsoftware** [comment]
Fantastic.
Thanks again.

**Pull request merged**
